### ISSUE TITLE
Support for getting active page index

### ISSUE THREAD

**Issue by MatthewScholefield** [roginfarrer/react-aria-carousel#1]
Hello! This project looks awesome, but I'm looking to synchronize another react component (a steps component) with the active carousel page index. I see it's already within the carousel state; is there a simple way the API could be extended to allow subscribing to it? I'm not sure if it would work but perhaps something like:

```typescript
export const useActivePageIndex = () => {
    const { carouselState } = useCarouselContext();
    return carouselState.activePageIndex;
}
```

Note: Right now I can't directly do this because `useCarouselContext` is not exposed.

**Comment by roginfarrer** [comment]
I actually ran into this issue just the other day, too. I was thinking of adding a prop that would allow you to listen to the page index changing:

```tsx
export const App = () => {
  const [pageIndex, setPageIndex] = useState()

  return (
    <div>
      <Carousel 
        onActivePageIndexChange={(index) => {
          setPageIndex(index)
        }}
      />
      {pageIndex}
    </div>
  )
}
```

Out of curiosity, would you ever need to initialize the carousel with a different active page than the first one?

**Comment by MatthewScholefield** [comment]
I was planning to just wrap the other controllable visual indicators in `<CarouselItem>` so in my case I wouldn't need it to be controlled. And similarly I wouldn't need to initialized it with a different page.
